version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: veritasMagna
    restart: always
    environment:
      - MYSQL_DATABASE=veritas_capital
      - MYSQL_ROOT_PASSWORD=bestBank
    ports:
      - '3308:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local